routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

 Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('admin')->group(function () {
    Route::resource ('category', 'CategoryController', [
        'except' => 'show'
    ]);
    Route::name('maintenance.index')->get('maintenance', 'AdminController@index');
    Route::name('maintenance.destroy')->delete('maintenance', 'AdminController@destroy');
});

//Le groupe  servira plus tard quand à ajouter d’autres routes
Route::middleware('auth')->group(function () {
    Route::resource('image', 'ImageController', [
        'only' => ['create', 'store', 'destroy', 'update']
    ]);
});

//affichage par catégorie
Route::name('category')->get('category/{slug}', 'ImageController@category');


Route::name('user')->get('user/{user}', 'ImageController@user');

Route::resource('image', 'ImageController', [
    'only' => ['create', 'store', 'destroy']
]);

//route pour deploiement
Route::get('/install', function(){
    Artisan::call('migrate:fresh',[
        '--seed' => true,
        '--force' => true,
    ]);
    echo 'ok';
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Album') }}</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    @yield('css')
</head>
<body>
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ route('home') }}"><img src="/img/logo.png" alt="logo"> </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
   
            <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle
                        @isset($category)
                            {{ currentRoute(route('category', $category->slug)) }}
                        @endisset
                            " href="#" id="navbarDropdownCat" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @lang(' Oeuvres par catégorie ')
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownCat">
                        @foreach($categories as $category)
                            <a class="dropdown-item" href="{{ route('category', $category->slug) }}">{{ $category->name }}
                            </a>
                        @endforeach
                    </div>
                </li>

        {{-- gestion categories admin --}}
        @admin
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle{{ currentRoute(
                            route('category.create'), 
                            route('category.index'),
                            route('category.edit', request()->category?: 0) ,
                            route('maintenance.index')
                        )}}" href="#" id="navbarDropdownGestCat" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @lang('Administration')
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownGestCat">
                <a class="dropdown-item" href="{{ route('category.create') }}">
                    <i class="fas fa-plus fa-lg"></i> @lang('Ajouter une catégorie')
                </a>
                <a class="dropdown-item" href="{{ route('category.index') }}">
                    <i class="fas fa-wrench fa-lg"></i> @lang('Gérer les catégories')
                </a>
                <a class="dropdown-item" href="{{ route('maintenance.index') }}">
                    <i class="fas fa-cogs fa-lg"></i> @lang('Maintenance')
                </a>
                
            </div>
        </li>
    @endadmin
    {{-- formulaire d’ajout d’une image  --}}
    @auth
    <li class="nav-item{{ currentRoute(route('image.create')) }}"><a class="nav-link" href="{{ route('image.create') }}">@lang('Ajouter une image')</a></li>
@endauth

        <ul class="navbar-nav ml-auto">
            @guest
            <li class="nav-item{{ currentRoute(route('login')) }}"><a class="nav-link" href="{{ route('login') }}">@lang('Connexion')</a></li>
            <li class="nav-item{{ currentRoute(route('register')) }}"><a class="nav-link" href="{{ route('register') }}">@lang('Inscription')</a></li>
            @else
                <li class="nav-item">
                    <a id="logout" class="nav-item" href="{{ route('logout') }}">@lang('Déconnexion')</a>
                    <li class="nav-item" href="{{route('logout') }}"></li>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hide">
                        {{ csrf_field() }}
                    </form>
                </li>
            @endguest
        </ul>
    </div>
</nav>

@if (session('ok'))
<div class="container">
    <div class="alert alert-dismissible alert-success fade show" role="alert">
        {{ session('ok') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>
@endif


@yield('content')
<script src="{{ asset('js/app.js') }}"></script>
@yield('script')
<script>
    $(function() {
        $('#logout').click(function(e) {
            e.preventDefault();
            $('#logout-form').submit()
        })
    })
</script>
</body>
</html>

resources/views/layouts/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container py-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                @yield('card')
            </div>
        </div>
    </div>
@endsection